name: Test libxcselect

on: push

jobs:
  test-xcselect:
    strategy:
      fail-fast: false
      matrix:
        macos-version: [13, 14, 15]
        policy: ['LATEST', 'MATCHING_ONLY', 'MATCHING_PREFERRED']
    runs-on: macos-${{ matrix.macos-version }}
    steps:
      - uses: actions/checkout@v4

      - run: make POLICY="${POLICY}" test
        env:
          POLICY: ${{ matrix.policy }}
