name: Test libxcselect

on: push

jobs:
  test-xcselect:
    strategy:
      fail-fast: false
      matrix:
        macos-version: [13, 14, 15]
        policy: ['LATEST', 'MATCHING_ONLY', 'MATCHING_PREFERRED']
        xcode-version: ['15.0.1', '15.1', '15.2']
        include:
          - macos-version: 15
            xcode-version: '16.2_beta_3'
          - macos-version: 15
            xcode-version: '16.1'
          - macos-version: 15
            xcode-version: '16'
          - macos-version: 15
            xcode-version: '15.4'
          - macos-version: 14
            xcode-version: '16.1'
          - macos-version: 14
            xcode-version: '16'
          - macos-version: 14
            xcode-version: '15.4'
          - macos-version: 14
            xcode-version: '15.3'
          - macos-version: 13
            xcode-version: '14.3.1'
          - macos-version: 13
            xcode-version: '14.2'
          - macos-version: 13
            xcode-version: '14.1'
        exclude:
          - macos-version: 16
            xcode-version: '15.2'
          - macos-version: 16
            xcode-version: '15.1'
          - macos-version: 16
            xcode-version: '15.0.1'
    runs-on: macos-${{ matrix.macos-version }}
    steps:
      - uses: actions/checkout@v4

      - run: make POLICY="${POLICY}"
        env:
          POLICY: ${{ matrix.policy }}

      - run: sudo xcode-select --switch "/Applications/Xcode_${XCODE_VERSION}.app"
        env:
          XCODE_VERSION: ${{ matrix.xcode-version }}

      - run: make test
